#!/usr/bin/env bash
# sync markdown prompts into edge function bundles (required for supabase deploy)
set -euo pipefail
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
SRC="${ROOT}/supabase/prompts/plan_generate_v1.md"
DEST_SHARED="${ROOT}/supabase/functions/_shared/plan/plan_generate_v1.md"
DEST_FN="${ROOT}/supabase/functions/plan-generate/plan_generate_v1.md"
BUNDLE="${ROOT}/supabase/functions/plan-generate/plan_generate_v1.bundle.ts"

cp "${SRC}" "${DEST_SHARED}"
cp "${SRC}" "${DEST_FN}"

python3 - <<'PY' "${SRC}" "${BUNDLE}"
import pathlib, sys
src, dest = sys.argv[1], sys.argv[2]
text = pathlib.Path(src).read_text(encoding="utf-8")
escaped = text.replace("\\", "\\\\").replace("`", "\\`")
out = f"""// auto-generated by scripts/sync-prompts.sh — do not edit\n// source: supabase/prompts/plan_generate_v1.md\nexport const planGenerateTemplate = `{escaped}`;\n"""
pathlib.Path(dest).write_text(out, encoding="utf-8")
print(f"wrote {dest}")
PY
